name: Check broken links

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 5 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: "checklink_config.json"
          max-depth: 3

      - name: Archive Broken Links List
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: broken-links.json
          path: /brokenLinks.json
          retention-days: 5
